# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6b9d4c64edafbf22ce95eb8ae9f3282c924f05e6625c1c375b2579cf1016e023d099151c22231eb8ea2c593cdaecffc8ee79d2d54a9bc9c79dea157081f3a9a

test:
  secret_key_base: 086dd99b3e4696c1825f893fffafbf1ff71b0a416d1afb01629e46521c2496ac0edd08c04d825c385bea9caab871d45e1b94161c02f79c16016463b78733e5aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
